# This is a basic workflow to help you get started with Actions

name: 'Terraform Deployment'

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-dev:
    name: 'Terraform Dev'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_AD_SECRETS }}


      - name: Set Terraform Environment Variables
        run: |
         echo '${{ secrets.AZURE_AD_SECRETS }}' > azure_creds.json
         echo "ARM_CLIENT_ID=$(jq -r .clientId azure_creds.json)" >> $GITHUB_ENV
         echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret azure_creds.json)" >> $GITHUB_ENV
         echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId azure_creds.json)" >> $GITHUB_ENV
         echo "ARM_TENANT_ID=$(jq -r .tenantId azure_creds.json)" >> $GITHUB_ENV



      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v3
      - run: |
          cd dev
          tflint --init
          tflint --recursive

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Security Scan
        run: checkov -d . || true  # Ignore errors but still scan
            
          

      - name: Terraform Init (dev)
        run: |
          cd dev
          terraform init
          working-directory: dev

      - name: Terraform Validate (dev)
        run: |
          cd dev
          terraform validate
          working-directory: dev

      - name: Terraform Plan (dev)
        run: |
          cd dev
          terraform plan -var-file="terraform.tfvars" -input=false
          working-directory: dev

      - name: Terraform Apply (dev)
        run: |
          cd dev
          terraform apply -var-file="terraform.tfvars" -auto-approve -input=false
          working-directory: dev

  terraform-qa:
    name: 'Terraform QA'
    runs-on: ubuntu-latest
    environment: qa
    needs: terraform-dev  # Runs after dev completes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Terraform Environment Variables
        run: |
         echo "${{ secrets.AZURE_AD_SECRETS }}" > azure_creds.json
         echo "ARM_CLIENT_ID=$(jq -r .client_id azure_creds.json)" >> $GITHUB_ENV
         echo "ARM_CLIENT_SECRET=$(jq -r .client_secret azure_creds.json)" >> $GITHUB_ENV
         echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscription_id azure_creds.json)" >> $GITHUB_ENV
         echo "ARM_TENANT_ID=$(jq -r .tenant_id azure_creds.json)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v3
      - run: |
          cd qa
          tflint --init
          tflint --recursive

      - name: Run Checkov Security Scan
        run: |
          checkov -d . || true  # Forces Checkov to always return success

          directory: qa

      - name: Terraform Init (qa)
        run: |
          cd qa
          terraform init
          working-directory: qa

      - name: Terraform Validate (qa)
        run: |
          cd qa
          terraform validate
          working-directory: qa

      - name: Terraform Plan (qa)
        run: |
          cd qa
          terraform plan -var-file="terraform.tfvars" -input=false
          working-directory: qa

      - name: Manual Approval for QA
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Apply (qa)
        run: |
          cd qa
          terraform apply -var-file="terraform.tfvars" -auto-approve -input=false
          working-directory: qa

  terraform-prod:
    name: 'Terraform Prod'
    runs-on: ubuntu-latest
    environment: prod
    needs: terraform-qa  # Runs after QA completes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Terraform Environment Variables
        run: |
          echo "${{ secrets.AZURE_AD_SECRETS }}" > azure_creds.json
          echo "ARM_CLIENT_ID=$(jq -r .client_id azure_creds.json)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r .client_secret azure_creds.json)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscription_id azure_creds.json)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r .tenant_id azure_creds.json)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v3
      - run: |
          cd prod
          tflint --init
          tflint --recursive

      - name: Run Checkov Security Scan
        run: |
         checkov -d . || true  # Forces Checkov to always return success

          directory: prod

      - name: Terraform Init (prod)
        run: |
          cd prod
          terraform init
          working-directory: prod

      - name: Terraform Validate (prod)
        run: |
          cd prod
          terraform validate
          working-directory: prod

      - name: Terraform Plan (prod)
        run: |
          cd prod
          terraform plan -var-file="terraform.tfvars" -input=false
          working-directory: prod
          

      - name: Manual Approval for Prod
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Apply (prod)
        run: |
          cd prod
          terraform apply -var-file="terraform.tfvars" -auto-approve -input=false
          working-directory: prod
